[build]
  publish = "."

[[headers]]
  for = "/model/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.bin"
  [headers.values]
    Content-Type = "application/octet-stream"
    Access-Control-Allow-Origin = "*"
